---
title: "Assignment One"
output:  
  html_document:
    theme: flatly
    css: default.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Department of Psychology, Stockholm University

Human Development: Attachment and Relational Contexts of Lifespan Development

Joel Gruneau Brulin, PhD

April 8th, 2022

Word count: 1500 words

**1) Explain the normative development of the attachment relationship. Highlight the evolutionary function of the attachment system and specify what is unique about the attachment relationship based on the concepts of safe haven and secure base.
 2) Describe the essential features of the three organized attachments styles according to Ainsworth´s classification. Use both a parent-, context- and child perspective to highlight why a person may develop respective classification.**

Attachment theory is an evolutionary based theory about the development of an affectionate bond between a child and its caregiver (Cassidy, 2016). Coined by John Bowlby, a psychoanalyst and psychiatrist, attachment theory draws from multiple disciplines such as evolution, ethology, cognitive science, cybernetics, and psychoanalysis (Granqvist, 2020). Bowlby, influenced by work with juveniles alongside James and Joyce Robertson, noticed that infants&#39; facial expressions conveying distress reliably manifested following separation from caregivers: First a face of protest, then despair, and lastly detachment (Cassidy, 2016). Although Bowlby was a psychoanalyst by trade (Granqvist, 2020), he doubted contemporary theories&#39; ability to explain predictable manifestations of infant facial expressions following separation. Bowlby&#39;s doubt was supported by ethological research (cf. Harlow and Lorenz) and notably by Anna Freud&#39;s and Dorothy Burlingham&#39;s research. They learned that children left with their parents in bomb-shelters during World War II fared better compared to children sent to the countryside (Granqvist, 2020). In other words, proximity with caregivers reliably predicted better adjustment in life compared exemplary nourishment (Cassidy, 2016).

Consequently, Bowlby emphasised the importance of continuity in caregiving and the quality off the caregiver-infant relationship (Cassidy, 2016). Bowlby hypothesized that humans had an innate, naturally selected, attachment system that desired security with an attachment figure (usually the mother) though physical proximity (Cassidy, 2016). To obtain proximity with the attachment system, the child engages in various attachment behaviours. For example, a child&#39;s locomotive behaviours (e.g., approaching and following) are active attachment behaviours increase the child&#39;s proximity to the mother (Cassidy, 2016).

Bowlby proposed that during the course of human evolution, the attachment system had evolved in the environment of evolutionary adaptedness where proximity-seeking behaviours with a caregiver were favoured in the genetic selection. In turn, such behaviours increased the likelihood of protection by a stronger and wiser attachment figure, and thus were advantageous for survival. Bowlby referred to such protection as a biological function of attachment behaviours because infants innately predisposed to seek proximity with their caregivers in the environment of evolutionary adaptedness were less likely to be killed by predators (Bretherton, 1992). Consequently, claiming humans to be pre-wired for attachment is underpinned in evolutionary science and further supported by Bowlby&#39;s identification that attachment forms even to abusive mothers (Cassidy, 2016).

Notably, the attachment relationship between infant and caregiver is asymmetrical. The attached child forms an affectionate bond (i.e., attachment relationship) with an attachment figure who is perceived as stronger and wiser. Moreover, the child looks to their attachment figure in times of distress (i.e., as a safe haven) and as a point of departure for exploration (i.e., as a secure base). As noted, this attachment relationship is characterized by physical proximity maintenance and separation distress. Additionally, the attached child engages is secure base and safe haven behaviours (Bretherton, 1992; Cassidy, 2016).

The attachment system facilitates attachment relationship formation and children appear to be born with sophisticated perceptual abilities that facilitate attachment (Cassidy, 2016). In that sense, the attachment system operates in synchrony with at least two other biological systems: The fear system and exploration system. In relation to the fear system, Bowlby noted that when afraid, children not only run away from something (e.g., danger) but also towards something else (e.g., comfort). All things equal, the attachment figure provides a _safe haven_ that the attached child can seek out in times of distress. In that sense, a safe haven refers the attachment figure being responsive and sensitive to the attached child&#39;s signalling of distress. In other words, a safe haven is the place to which the attached child returns to when experiencing distress. In relation to the exploration system, Mary Ainsworth&#39;s framework of a _secure base_ from which the attached child feels free to explore from best captures the complimentary functions of the attachment and exploration systems (Bretherton, 1992). Thus, a secure base relates to the attached trusting that they have someone to return to after exploratory adventures. In order to provide a secure base, the attachment figure must support exploration by encouraging and accepting exploration, being available if needed, and not unnecessarily interrupt the exploratory adventures (Cassidy, 2016).

The development of the attachment relationship can roughly be divided into four stages: The first phase lasts around 8-12 weeks and is characterized by extensive attachment signalling without discrimination. The second phase then lasts until the child is around 6-9-months-old and is characterized by more discriminative signalling at one or more attachment figures whom are perceived as most likely to provide stability. In the third phase, lasting until the child is around 3-years-old, the child learns to regulate their proximity to a discriminative attachment figure through their own locomotion (Zeifman &amp; Hazan, 2016). It should be noted that attachment formation has a sensitive period in the child&#39;s first year; if attachment has not formed by then, a maladaptive attachment is likelier to develop. Other things equal, all normal humans attach to their primary caregiver within the first 8-months of life (Zeifman &amp; Hazan, 2016) and thus, somewhat unsurprisingly, a prototypical attachment relationship has usually manifested when the child is 1-years-old (Cassidy, 2016). Lastly, in the fourth phase, interactions between the attached and attachment figure become characterized by communication (e.g., about shared goals) and negotiation; the child develops a theory of mind; and a goal-corrected partnership continuously develops from when the child is approximately 3-years-old and onwards (Zeifman &amp; Hazan, 2016).

Although a full-fledged attachment relationship has developed when the child is 1-years-old (Cassidy, 2016), the quality of attachment individually differs. Most broadly, attachment relationships can be conceived of as either _secure_ or _insecure_. A further differentiation can then be made within insecure attachments where _anxious/resistant_ attachments differ from _avoidant_ attachments. The three types of attachment relationships just listed make up the organized attachment styles identified by Mary Ainsworth (Bretherton, 1992).

A _secure_ attachment is marked by a dynamic interplay between exploration and attachment behaviours. A securely attached child feels free to explore the world but trusts the availability of the attachment figure, and thus eagerly seeks contact with their attachment figure upon experiencing distress or after brief separation. Notably, a secure attachment is the attachment style most likely to remain stable over time and predicts later socioemotional functions and executive functioning. The key element for developing security is caregiver sensitivity and availability. Caregiver sensitivity refers to how a caregiver interprets and responds to the attachment signalling and through caregiver sensitivity, the child learns what to expect in terms of availability of others; both in relation to attachment and exploration. However, if the attachment figure is ambivalent to the child&#39;s needs or unavailable (e.g., rejects the child), the child minimizes their attachment signalling and develops an _avoidant_ attachment. Thus, avoidantly attached children do not display much attachment signalling when separated from caregivers and reject their attachment figures upon reunion (e.g., mother&#39;s occupational duties could be perceived as rejective, and in turn facilitate attachment avoidance). Avoidantly attached children have a mental representation (a.k.a., internal-working-model) of the attachment figure being unavailable and operate in the world accordingly (Cassidy, 2016).

In contrast to a minimization of attachment signalling among avoidantly attached children, _anxious/resistant_ attachment is characterized by a sort of hyperactive attachment signalling. This maximization of attachment signalling is the consequence of inconsequential experiences from caregivers, making infants unsure of what to expect. Such uncertainty has been associated with parents&#39; own childhood-attachment anxiety (Main &amp; Hesse, 1990). Anxiously attached children have a low threshold of attachment activation, are less likely to be exploratory, and sometimes thought of as clingy. The minimized and maximized attachment signalling of avoidantly and anxiously attached children, respectively, likely acts as a self-fulfilling prophecy. That is, by anticipating rejection, more rejection is likely manifested which in turn reinforces avoidant attachment; by extensive clinginess, inconsequential responses likely manifest which in turn reinforce anxious attachment (Cassidy, 2016). Thus, behavioural manifestations of attachment behaviour are context-specific insofar as children react differently to distress and danger depending on the availability and sensitivity of caregivers (Crowell et al., 2016).

It should be noted that a principal attachment figure is not interchangeable. In other words, no number of friends or relatives can make up for the loss of a principal attachment figure, a tendency Bowlby termed monotropy. Consequently, such a loss increases the likelihood of developing an insecure attachment style. Furthermore, contextual factors such as socioeconomic risk are predictive of insecure attachment development (Cassidy, 2016). Maternal- and parental satisfaction are associated with security (Bretherton, 1992), but caregiver sensitivity appears to affect security formation the most. For caregivers to provide sensitivity, the caregiving system must activate. Such activation depends on both internal cues (e.g., hormones and parental state) and external cues (e.g., perceived environmental danger and infant state/behaviour); without caregiving system activation infants cannot survive. Ethologists have even proposed that infants&#39; babyish features evolved to activate the caregiving system (Cassidy, 2016).

Bowlby&#39;s theory of attachment has required little-to-no modification from its original formulation. Such a feat is uncommon within a scientific discipline advancing at a high phase like psychology, making his contribution that much more remarkable (Granqvist, 2020).

# References

Bretherton, I. (1992). The origins of attachment theory: John Bowlby and Mary Ainsworth. _Developmental Psychology, 28_(5), 759–775. https://doi.org/10.1037/0012-1649.28.5.759

Cassidy, J. (2016). The nature of the child&#39;s ties. In J. Cassidy &amp; P. R. Shaver (Eds.), _Handbook of attachment: Theory, research, and clinical applications_ (3rd ed., pp. 3–24). The Guilford Press.

Crowell, J. A., Fraley, R. C., &amp; Shaver, P. R. (2016). Measurement of individual differences in adolescent and adult attachment. In J. Cassidy &amp; P. R. Shaver (Eds.), _Handbook of attachment: Theory, research, and clinical applications_ (3rd ed., pp. 598–635). The Guilford Press.

Granqvist, P. (2020). _Attachment in religion and spirituality: A wider view._ Guilford Publications.

Main, M., &amp; Hesse, E. (1990). Parents&#39; unresolved traumatic experiences are related to infant disorganized attachment status: Is frightened and/or frightening parental behavior the linking mechanism? In M. T. Greenberg, D. Cicchetti, &amp; E. M. Cummings (Eds.), _Attachment in the preschool years: Theory, research, and intervention_ (pp. 161–182). The University of Chicago Press.

Zeifman, D. M., &amp; Hazan, C. (2016). Pair bonds as attachments: Mounting evidence in support of Bowlby&#39;s hypothesis. In J. Cassidy &amp; P. R. Shaver (Eds.), _Handbook of attachment: Theory, research, and clinical applications_ (3rd ed., pp. 416–434). The Guilford Press.